#+TITLE: A shopping list.

An optimum project for sharing a shopping list between opti-friends.

* Implementations

Two implementations are available : in-memory and database.

** In Memory

Nothing special to do in order to load the in-memory shopping list.
The list will be lost when the process quits.

** Database

Set the following env variables to enable the database implementation:

 1. OPTI_SHOPYLIST_MANAGER="DATABASE"
 2. OPTI_SHOPYLIST_DB_NAME="my-db-name"
 3. OPTI_SHOPYLIST_USERNAME="db-user"
 4. OPTI_SHOPYLIST_PASSWORD="password-for-db-user"

* Database

** Shopping item

Table =shopping_item= created by mito with the dao =shopping-item= in
the package :db of the project.

| field        | type        |
|--------------+-------------|
| product-name | varchar 128 |
| status       | char 4      |

See the [[https://github.com/fukamachi/mito][Mito]] library to find out how the table is created.

* Create executable

Run the following command to create the executable.
You'll need [[https://github.com/roswell/roswell][Roswell]]!

#+BEGIN_SRC sh
ros dump executable opti-shopylist.ros
#+END_SRC
